#!/usr/bin/gawk -f

##################################################################
BEGIN {
    split("", fields)
    split("", values)

    v_cnt = 0
    VALUE_SEP = "\034"
}

##################################################################
# Main
/^nid/ {
    f_cnt = split($0, fields, /\t/)
    nid = fields[2]
    for (i = 4; i <= f_cnt; ++i) {
	v_cnt = split(fields[i], values, VALUE_SEP)
	printf("set node(%s,%s) ", nid, values[1])
	if (v_cnt > 1) {
	    printf("{%s", values[2])
	    for (j = 3; j <= v_cnt; ++j) {
		printf(" %s", values[j])
	    }
	    printf("}")
	} else {
	    printf("{ }")
	}
	printf("\n")
    }
    printf("\n")
}
